### Basics

**********************  **START** **************************

* Python is a general purpose language.  Its applications are vast and varied

* Python is easy to learn and use. It is developer-friendly and high level programming language.

* Python language is more expressive means that it is more understandable and readable.

* Python is an interpreted language i.e. interpreter executes the code line by line at a time. This makes debugging easy and thus suitable for beginners.

* Python language is freely available at official web address. The source-code is also available. Therefore it is open source.

* Python has a large and broad library and provides rich set of modules and functions for rapid application development.

* In Python, we don't need to specify the type of variable because Python is a type infer language and smart enough to get variable type.

* Variables are case-sensitive

* Python allows us to assign a value to multiple variables in a single statement which is also known as multiple assignment.

**Basic data types in Python:**
* Int
* Float - Decimal
* Complex – complex numbers
* Boolean – True / False
* String  - Text

In [ ]:
print("Hello World!")

Hello World!

In [2]:
# Variable assignment ----------------------------
a,b,c=5,10,15
print(a)
print(b)
print(c)

# Data types ----------------------------
x = 1
y = 2.8
z = 1j
a= "True"
b=True

print(type(x))
print(type(y))
print(type(z))
print(type(a))
print(type(b))

5
10
15
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'bool'>

**String functions:**
* strip() – remove whitespaces
* len() – no of characters in string
* lower()
* upper()
* replace() – replace one string with another
* split() – split using a character
* input() – to accept user input from keyboard

In [3]:
## String functions ----------------------------
a = 'Hello, World!'
print(a[1])
b = "Hello, World!"
print(b[2:5])
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"
a = "Hello, World!"
print(len(a))
a = "Hello, World!"
print(a.lower())
a = "Hello, World!"
print(a.upper())
a = "Hello, World!"
print(a.replace("H", "J"))
a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']
print("Enter your name:")
x = input()
print("Hello, " + x)

e
llo
Hello, World!
13
hello, world!
HELLO, WORLD!
Jello, World!
['Hello', ' World!']
Enter your name:
nb,bm
Hello, nb,bm

* **Implicit Type conversion** – where Python is clear on what it should do

* **Explicit Type casting** – converting one data type into another explicitly
* int()
* float()
* str()

In [ ]:
# Explicit
num_int = 123
num_str = "456"

num_str = int(num_str) # comment out this line and see the result

num_sum = num_int + num_str
print("Sum of num_int and num_str:",num_sum)

Sum of num_int and num_str: 579

**Arithmetic operators**

In [ ]:
# Arithmetic operators ----------------------------

x = 15
y = 4

# Output: x + y = 19
print('x + y =',x+y)
# Output: x - y = 11
print('x - y =',x-y)
# Output: x * y = 60
print('x * y =',x*y)
# Output: x / y = 3.75
print('x / y =',x/y)
# Output: x // y = 3
print('x // y =',x//y)
# Output: x ** y = 50625
print('x ** y =',x**y)

x + y = 19
x - y = 11
x * y = 60
x / y = 3.75
x // y = 3
x ** y = 50625

**Comparision operators**

In [ ]:
# comparision operators ----------------------------

x = 10
y = 12

# Output: x > y is False
print('x > y  is',x>y)
# Output: x < y is True
print('x < y  is',x<y)
# Output: x == y is False
print('x == y is',x==y)
# Output: x != y is True
print('x != y is',x!=y)
# Output: x >= y is False
print('x >= y is',x>=y)
# Output: x <= y is True
print('x <= y is',x<=y)

x > y  is False
x < y  is True
x == y is False
x != y is True
x >= y is False
x <= y is True

**Logical operators**

In [4]:
# Logical operators ----------------------------

x = True
y = False

# Output: x and y is False
print('x and y is',x and y)
# Output: x or y is True
print('x or y is',x or y)
# Output: not x is False
print('not x is',not x)

x and y is False
x or y is True
not x is False

## Control flow

**If Else**

In [ ]:
#-------------------if else

a = 33
b = 200
if (b > a):
  print("b is greater than a");

a = 33
b = 200
if b > a:
  print("b is greater than a") # you will get an error without indentation

a = 33
b = 35 # change value and see
if a == b:
  print("a and b are equal")
else:
  print("a and b are not equal")

a = 200
b = 33 # change value and see
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

#shortcut syntax
if a > b: print("a is greater than b")

print("A") if a > b else print("B")

a = 200
b = 33 # change value and see
c=300
if a > b and c > a:
  print("Both conditions are True")

if a > b or a > c:
  print("At least one of the conditions are True")

b is greater than a
b is greater than a
a and b are not equal
a is greater than b
a is greater than b
A
Both conditions are True
At least one of the conditions are True

**Membership operators**

In [ ]:
# Membership operators ----------------------------

x = 24
y = 20
list = [10, 20, 30, 40, 50 ]

if  (x not in list):
   print("x is NOT present in given list")
else:
   print("x is  present in given list")

if ( y in list ):
   print("y is present in given list")
else:
   print("y is NOT present in given list")

x is NOT present in given list
y is present in given list

**Identity operators**

In [ ]:
# Identity operators ----------------------------

x = 5 # use None too
if (type(x) is int):
    print("true")
else:
    print("false")

x = 5.2
if (type(x) is not int):
    print("true")
else:
    print("false")

true
true

**While loop**

In [ ]:
#-------------------while loop
i = 1
while i < 6:
  print(i)
  i =i+ 1

0
1
2
3
4
5

**Break statement**

In [ ]:
#------------------break example
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3

**for loop**

In [ ]:
print(range(6))
#-------------------for loop
for x in range(6):
  print(x)
print('next loop')

for x in range(2, 6):
  print(x)
print('next loop')

for x in range(2, 30, 3):
  print(x)
print('next loop')

for x in range(6):
  print(x)
  #break
else:
  print("Finally finished!")

range(0, 6)
0
1
2
3
4
5
next loop
2
3
4
5
next loop
2
5
8
11
14
17
20
23
26
29
next loop
0
1
2
3
4
5
Finally finished!

## Collection data types

* List is a collection which is ordered and changeable. Allows duplicate members.
* Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
* Set is a collection which is unordered and unindexed. No duplicate members.
* Dictionary is a collection which is unordered, changeable and indexed. No duplicate members.

* Use a tuple when you know what information goes in the container that it is. For example, when you want to store a person’s credentials for your website. think of it as a row in a DB table.  It is read-only

* But when you want to store similar elements, like in an array in C++, you should use a list.  Think of it as a collection of similar values.

* In practical applications, lists are very nice to sort and have order while sets are nice to use when you don't want duplicates and don't care about order.  You can use set operations on sets.

* Use a dictionary if the purpose is to store key value pairs like configuration settings.



---

**Lists**

* len() - returns no of elements
* append() - Adds an element at the end of the list
* insert() - Adds an element at the specified position
* remove() - Removes the item with the specified value
* pop() -  removes the specified index, (or the last item if index is not specified)
* del – can be used for a member or the list itself
* clear() - Removes all the elements from the list
* count() - Returns the number of elements with the specified value
* extend() - Add the elements of a list (or any iterable), to the end of the current list
* index() - Returns the index of the first element with the specified value
* reverse()
* sort()

In [ ]:
ls1=[1,2,3]
ls2=[4,5,6]
ls3=[ls1,ls2]
ls4=[ls3,ls1]
ls5=[ls4,ls3]

print(ls1)
print(ls3)
print(ls4)
print(ls5)

[1, 2, 3]
[[1, 2, 3], [4, 5, 6]]
[[[1, 2, 3], [4, 5, 6]], [1, 2, 3]]
[[[[1, 2, 3], [4, 5, 6]], [1, 2, 3]], [[1, 2, 3], [4, 5, 6]]]

In [ ]:
ls1=[1,2,3]
tup1=tuple(ls1)
print(type(tup1))

<class 'tuple'>

In [ ]:
## Lists--------------------

for x in "banana":
  print(x)

thislist = ["apple", "banana", "cherry"]
print(thislist)

thislist = ["apple", "banana", "cherry"]
print(thislist[1])

thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

thislist = ["apple", "banana", "cherry"]
print(len(thislist))

thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.pop() # can take index as well (pop(1))
print(thislist)

thislist = ["apple", "banana", "cherry"]
del thislist
#print(thislist) #this will cause an error because "thislist" no longer exists.

thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

thislist = ["apple", "banana", "apple"]
print(thislist.count("apple"))

thislist1 = ["apple", "banana", 3]
thislist2 = ("fig", "guava")
thislist1.extend(thislist2)
print(thislist1)

thislist = ["apple", "banana", "cherry"]
print(thislist.index("banana"))

thislist = ["apple", "banana", "cherry"]
thislist.reverse()
print(thislist)

thislist = ["apple", "cherry", "banana"]
thislist.sort()
print(thislist)

b
a
n
a
n
a
['apple', 'banana', 'cherry']
banana
['apple', 'blackcurrant', 'cherry']
apple
banana
cherry
3
['apple', 'banana', 'cherry', 'orange']
['apple', 'orange', 'banana', 'cherry']
['apple', 'cherry']
['apple', 'banana']
[]
2
['apple', 'banana', 3, 'fig', 'guava']
1
['cherry', 'banana', 'apple']
['apple', 'banana', 'cherry']

**Tuples**

In [ ]:
## Tuples--------------------

thistuple = ('physics', 'chemistry', 1997, 2000)
print(thistuple)

thistuple = ('physics', 'chemistry', 1997, 2000)
print(thistuple[1])

thistuple = ('physics', 'chemistry', 1997, 2000)
#thistuple[1] = 'abc' # raises error
# The values will remain the same:
print(thistuple)

thistuple = ('physics', 'chemistry', 1997, 2000)
for x in thistuple:
  print(x)

thistuple = ('physics', 'chemistry', 1997, 2000)
print(len(thistuple))

thistuple = ('physics', 'chemistry', 1997, 2000)
print(thistuple.index(1997))

thistuple = ('physics', 'chemistry', 1997, 2000)
del thistuple
#print(thistuple) #this will raise an error because the tuple no longer exists

('physics', 'chemistry', 1997, 2000)
chemistry
('physics', 'chemistry', 1997, 2000)
physics
chemistry
1997
2000
4
2

**Sets**

* difference() - Returns a set containing the difference between two or more sets
* intersection() - Returns a set, that is the intersection of two other sets
* isdisjoint() - Returns True if the intersection is null
* issubset() - Returns whether another set contains this set or not
* issuperset() - Returns whether this set contains another set or not
* union() - Return a set containing the union of sets

In [ ]:
## Sets--------------------

thisset = {1,2,3}
print(thisset)

thisset = {1,2,3}

for x in thisset:
  print(x)

thisset = {1,2,3}
print(4 in thisset)

thisset = {1,2,3}
thisset.add(4)
print(thisset)

thisset = {1,2,3}
thisset.update([4,5,6])
print(thisset)

thisset = {1,2,3}
print(len(thisset))

thisset = {1,2,3}
thisset.remove(2)
print(thisset)


thisset = {1,2,3}
thisset.clear()
print(thisset)

thisset = {1,2,3}
del thisset
#print(thisset)

# initialize A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
C = {1,2}

print(A.union(B))
print(A.intersection(B))
print(A.isdisjoint(C))
print(A.issuperset(C))
print(A.issubset(C))
print(A.difference(B))
print(B.difference(A))

{1, 2, 3}
1
2
3
False
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6}
3
{1, 3}
set()
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
False
True
False
{1, 2, 3}
{8, 6, 7}

**Dictionaries**

* items() - Returns a list containing the a tuple for each key value pair
* keys() - Returns a list containing the dictionary's keys
* values() - Returns a list of all the values in the dictionary

In [ ]:
## Dictionaries--------------------

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
x = thisdict["model"]
print(x)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["year"] = 2018

for x in thisdict:
  print(x)

for x in thisdict.keys():
  print(x)

for x in thisdict.values():
  print(x)

for x, y in thisdict.items():
  print(x, y)

print(len(thisdict))

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red" # add new one
print(thisdict)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("model")
print(thisdict)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict
#print(thisdict) #this will cause an error because "thislist" no longer exists.

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.clear()
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang
brand
model
year
brand
model
year
Ford
Mustang
2018
brand Ford
model Mustang
year 2018
3
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}
{'brand': 'Ford', 'year': 1964}
{}

In [ ]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": [1,2,3]
}

ls=[100,200,thisdict]
print(ls)
print(ls[2]["year"][1])

[100, 200, {'brand': 'Ford', 'model': 'Mustang', 'year': [1, 2, 3]}]
2

More examples

https://www.programiz.com/python-programming/examples